version: 1
name: "Bug report"
about: "Use this form to report unexpected behaviour or errors. If this is a security vulnerability, do NOT open a public issue — see SECURITY.md for private reporting."
title: "[bug] {short_description}"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide a minimal, reproducible example and any logs or tracebacks that help diagnose the issue.
  - type: input
    id: short_description
    attributes:
      label: "Short summary"
      description: "One-line description of the problem (used in the issue title)."
      placeholder: "e.g. Crash when saving a sample record"
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Step-by-step instructions to reproduce the problem. Keep it minimal and exact."
      placeholder: |
        1. Do X
        2. Do Y
        3. Observe Z
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happened, including error messages or incorrect output."
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs / tracebacks"
      description: "Paste error tracebacks, console output or server logs. Wrap large outputs in triple backticks."
      placeholder: "Traceback (most recent call last):\n  ..."
  - type: input
    id: reproduction_url
    attributes:
      label: "Minimal reproduction (optional)"
      description: "Link to a minimal repro (repository, gist, or paste). Very helpful."
      placeholder: "https://github.com/your/repro"
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is the issue for your workflow?"
      options:
        - label: "blocker (data loss / crash)"
          value: "blocker"
        - label: "critical (major functionality broken)"
          value: "critical"
        - label: "major (important but workable)"
          value: "major"
        - label: "minor (small bug / cosmetic)"
          value: "minor"
        - label: "trivial (typo / docs)"
          value: "trivial"
      required: true
  - type: input
    id: forenlims_version
    attributes:
      label: "ForenLIMS version / commit"
      description: "Version, tag or commit SHA where the bug was observed (if known)."
      placeholder: "e.g. branch main @ abc1234"
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Python version, database and other environment details."
      placeholder: "e.g. Ubuntu 22.04, Python 3.11, PostgreSQL 15"
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm before submitting"
      options:
        - label: "I have searched for existing issues and PRs"
          value: "checked_searched"
        - label: "I can reproduce this problem consistently"
          value: "checked_repro"
        - label: "I did not include any secrets or credentials in this report"
          value: "checked_no_secrets"
  - type: markdown
    attributes:
      value: |
        Thanks — a maintainer will triage this issue. If the problem is security-sensitive, follow SECURITY.md for private reporting instead of
