version: 1
name: "Bug report"
description: "Report unexpected behaviour or errors. For security issues, do NOT open a public issue — see SECURITY.md."
title: "[bug] {short_description}"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please provide a minimal, reproducible example and any logs or tracebacks that help diagnose the issue.
  - type: input
    id: short_description
    attributes:
      label: "Short summary"
      description: "One-line description of the problem (used in the issue title)."
      placeholder: "e.g. Crash when saving a sample record"
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Step-by-step instructions to reproduce the problem. Keep it minimal and exact."
      placeholder: |
        1. Do X
        2. Do Y
        3. Observe Z
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happened, including error messages or incorrect output."
  - type: textarea
    id: logs
    attributes:
      label: "Relevant logs / tracebacks"
      description: "Paste error tracebacks, console output or server logs. Wrap large outputs in triple backticks."
      placeholder: "Traceback (most recent call last):\n  ..."
  - type: input
    id: reproduction_url
    attributes:
      label: "Minimal reproduction (optional)"
      description: "Link to a minimal repro (repository, gist, or paste)."
      placeholder: "https://github.com/your/repro"
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is the issue for your workflow?"
      options:
        - "blocker (data loss / crash)"
        - "critical (major functionality broken)"
        - "major (important but workable)"
        - "minor (small bug / cosmetic)"
        - "trivial (typo / docs)"
  - type: input
    id: forenlims_version
    attributes:
      label: "ForenLIMS version / commit"
      description: "Version, tag or commit SHA where the bug was observed (if known)."
      placeholder: "e.g. branch main @ abc1234"
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Python version, database and other environment details."
      placeholder: "e.g. Ubuntu 22.04, Python 3.11, PostgreSQL 15"
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm before submitting"
      options:
        - "I have searched for existing issues and PRs"
        - "I can reproduce this problem consistently"
        - "I did not include any secrets or credentials in this report"
  - type: markdown
    attributes:
      value: |
        Thanks — a maintainer will triage this issue. If the problem is security-sensitive, follow SECURITY.md for private reporting instead of opening a public issue.
