version: 1
name: "Feature request"
about: "Propose a new feature or enhancement. Describe the user need, proposed solution and benefits."
title: "[feature] {short_description}"
labels: ["enhancement", "feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for proposing an improvement. Please provide a clear user story, the proposed solution, and why this change is valuable. If this is a large change, link any designs or related discussion.
  - type: input
    id: short_description
    attributes:
      label: "Short summary"
      description: "One-line description used in the issue title."
      placeholder: "e.g. Add CSV export for sample results"
      required: true
  - type: textarea
    id: user_story
    attributes:
      label: "User story / Use case"
      description: "Describe who benefits and what they want to achieve (e.g. As a ..., I want ..., so that ...)."
      placeholder: "As a lab technician, I want to export results to CSV so that I can share data with collaborators."
      required: true
  - type: textarea
    id: proposed_solution
    attributes:
      label: "Proposed solution"
      description: "Outline a possible implementation or API/UX changes. Optional but helpful."
      placeholder: "Add an `export` endpoint that streams CSV, or a UI button on the results page."
  - type: textarea
    id: benefits
    attributes:
      label: "Benefits / Rationale"
      description: "Why is this feature important? Describe expected improvements or use cases."
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Other approaches evaluated (e.g. third-party tools, manual workaround)."
  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How urgent/important is this feature?"
      options:
        - label: "High"
          value: "high"
        - label: "Medium"
          value: "medium"
        - label: "Low"
          value: "low"
      required: true
  - type: input
    id: estimate
    attributes:
      label: "Estimated effort (optional)"
      description: "Rough estimate (small/medium/large, story points, or hours)."
      placeholder: "e.g. small / 3 SP / ~8h"
  - type: input
    id: designs_url
    attributes:
      label: "Designs / mockups (optional)"
      description: "Link to design files, screenshots, or a prototype."
      placeholder: "https://figma.com/..., https://gist.github.com/..."
  - type: input
    id: related
    attributes:
      label: "Related issues / PRs (optional)"
      description: "Link existing discussions, issues or PRs."
      placeholder: "#123, https://github.com/..."
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Please confirm before submitting"
      options:
        - label: "I searched existing issues and PRs"
          value: "checked_searched"
        - label: "I provided a clear user story and acceptance criteria"
          value: "checked_user_story"
        - label: "I am willing to help implement or test this change"
          value: "checked_help"
        - label: "I did not include any secrets or credentials"
          value: "checked_no_secrets"
  - type: markdown
    attributes:
      value: |
        Thanks — a maintainer will triage this request. If the change has security implications, follow SECURITY.md for private reporting instead of opening a public issue.
